"""pipeline/url_witness — defensive witness for URL claims.

Production motivation (task #171 L3, 2026-06-03): D-Ticket query produced
"Hier ist der Offizielle Website-Link: https://www.d-festival.de/" — a
hallucinated URL graded 🟢 quasifact by the standard tribunal (single
witness, no URL-existence verification). Worst-case failure: high-
confidence false-fact about a fabricated domain.

Defense doctrine: extract URLs from claim text + check whether each was
in the actual web-search results for this turn. URLs NOT in search
context were generated by the LLM from training-recall → high
hallucination risk → cap tier at nullfact (not factfact / quasifact).

This is the third layer of D-Ticket-class defense:
  L1 — RESEARCH_TRIGGERS heuristic catches "wo bekomme" → forces search
  L2 — OLLAMA_KEEP_ALIVE=24h keeps classifier warm → no silent skip
  L3 — url_witness caps tier on ungrounded URLs → no quasifact-on-hallucination

Doctrine:
  - [[judex_non_calculat]] — deterministic verification for verifiable
    claim-classes (URLs are deterministically checkable via search-context)
  - [[propaganda_over_ransomware]] — URL fabrication graded as fact is a
    canonical "silent confident" failure mode; cap by default
  - [[ehrlich_stumm_doctrine]] — if can't verify URL exists in context,
    fall back to honest nullfact

Public API:
  extract_urls(text) -> list[str]
  classify_url_claim(claim_text, search_urls) -> dict
  has_ungrounded_url(claim_text, search_urls) -> bool
"""

from __future__ import annotations

import re
from typing import List, Optional
from urllib.parse import urlparse


# Match http/https URLs in text. Strips common trailing punctuation
# that ends sentences but is not part of the URL.
_URL_RX = re.compile(r"https?://[^\s\)\]\>\"<]+")
_TRAIL_PUNCT = ".,;:!?])"


def extract_urls(text: str) -> List[str]:
    """Find http/https URLs in `text`. Returns list (in order of appearance).

    Strips trailing sentence punctuation that's commonly attached to URLs
    in flowing prose: "Siehe https://example.com." → "https://example.com".
    Markdown link tail "])" also stripped.
    """
    if not text:
        return []
    out = []
    for m in _URL_RX.finditer(text):
        u = m.group(0)
        # Strip trailing punctuation that's almost certainly not part of the URL
        while u and u[-1] in _TRAIL_PUNCT:
            u = u[:-1]
        if u:
            out.append(u)
    return out


def normalize_url(u: str) -> str:
    """Normalize for comparison: lowercase scheme + domain, strip trailing /.

    Compares structurally identical URLs even if surface form differs:
      "https://Example.COM/Foo/" == "https://example.com/Foo"
    Note: path is case-PRESERVING (paths are case-sensitive on most servers).
    """
    if not u:
        return ""
    try:
        p = urlparse(u)
        if not p.scheme or not p.netloc:
            return u.lower()
        scheme = p.scheme.lower()
        netloc = p.netloc.lower()
        path = p.path.rstrip("/")
        return f"{scheme}://{netloc}{path}"
    except Exception:
        return u.lower()


def classify_url_claim(claim_text: str, search_urls: Optional[List[str]]) -> dict:
    """Check whether URLs in claim_text were grounded in the search results.

    Args:
        claim_text: a single claim sentence/paragraph from LLM output
        search_urls: list of URLs from the web-search results for this turn.
                     If empty/None, treat all URLs in claim as ungrounded.

    Returns dict with:
        is_url_claim:        bool  — claim contains at least one URL
        claim_urls:          list  — URLs found in claim
        in_search:           list  — URLs that appeared in search context
        ungrounded:          list  — URLs NOT in search context (hallucination risk)
        suggested_tier_cap:  str | None — "nullfact" if ungrounded URLs present
        reason:              str  — short explanation
    """
    urls = extract_urls(claim_text)
    if not urls:
        return {
            "is_url_claim": False,
            "claim_urls": [],
            "in_search": [],
            "ungrounded": [],
            "suggested_tier_cap": None,
            "reason": "no_urls_in_claim",
        }

    search_norm = set(normalize_url(u) for u in (search_urls or []) if u)

    in_search = []
    ungrounded = []
    for u in urls:
        if normalize_url(u) in search_norm:
            in_search.append(u)
        else:
            ungrounded.append(u)

    if ungrounded:
        return {
            "is_url_claim": True,
            "claim_urls": urls,
            "in_search": in_search,
            "ungrounded": ungrounded,
            "suggested_tier_cap": "nullfact",
            "reason": "ungrounded_urls_present" if search_urls
                      else "no_search_context_available",
        }

    return {
        "is_url_claim": True,
        "claim_urls": urls,
        "in_search": in_search,
        "ungrounded": [],
        "suggested_tier_cap": None,
        "reason": "all_urls_in_search_context",
    }


def has_ungrounded_url(claim_text: str, search_urls: Optional[List[str]]) -> bool:
    """Convenience: True if claim has URLs not in search context."""
    return bool(classify_url_claim(claim_text, search_urls)["ungrounded"])


__all__ = [
    "extract_urls",
    "normalize_url",
    "classify_url_claim",
    "has_ungrounded_url",
]
